config/routes.rb
DvdManager::Application.routes.draw do
  
  resources :actors
  resources :directors
  resources :dvds
  
  root :to => 'dvds#index'
end

app/models/actor.rb
class Actor < Person
  attr_accessible :dvd_ids

  has_many :casts, :dependent => :destroy
  has_many :dvds, :through => :casts
end

app/models/cast.rb
class Cast < ActiveRecord::Base
  belongs_to :actor
  belongs_to :dvd
end

app/models/director.rb
class Director < Person
  has_many :dvds
end

app/models/dvd.rb
class Dvd < ActiveRecord::Base
  attr_accessible :name, :release_date_at, :summary, :asin, :director_id, :actor_ids
  
  belongs_to :director
  has_many   :casts
  has_many   :actors, :through => :casts
  
  validates_presence_of :name, :summary
  validates_uniqueness_of :name
end

app/models/person.rb
class Person < ActiveRecord::Base
  GENDERS = ['Male', 'Female']

  attr_accessible :date_of_birth_at, :gender, :name
  
  validates_presence_of :name, :gender
  validates_uniqueness_of :name  
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  respond_to :html
  
  before_filter :find_actor, :only => [:show, :edit, :update, :destroy]

  def index
    @actors = Actor.all
  end

  def show
  end

  def new
    @actor = Actor.new
  end

  def edit
  end

  def create
    @actor = Actor.new(params[:actor])
    
    if @actor.save
      redirect_to @actor, notice: 'Actor was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @actor.update_attributes(params[:actor])
      redirect_to @actor, notice: 'Actor was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @actor.destroy
    redirect_to actors_url, notice: 'Actor was successfully deleted.'
  end

  private

  def find_actor
    @actor = Actor.find_by_id(params[:id])
    redirect_to actors_url, :flash => {:error => 'Actor not found.'} unless @actor
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  respond_to :html

  before_filter :find_director, :only => [:show, :edit, :update, :destroy]

  def index
    @directors = Director.all
  end

  def show
  end

  def new
    @director = Director.new
  end

  def edit
  end

  def create
    @director = Director.new(params[:director])

    if @director.save
      redirect_to @director, notice: 'Director was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @director.update_attributes(params[:director])
      redirect_to @director, notice: 'Director was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @director.destroy
    redirect_to directors_url, notice: 'Director was successfully deleted.'
  end

  private

  def find_director
    @director = Director.find_by_id(params[:id])
    redirect_to directors_url, :flash => {:error => 'Director not found.'} unless @director
  end
end

app/controllers/dvds_controller.rb
class DvdsController < ApplicationController
  respond_to :html

  before_filter :find_dvd, :only => [:show, :edit, :update, :destroy]

  def index
    @dvds = Dvd.all
  end

  def show
  end

  def new
    @dvd = Dvd.new
  end

  def edit
  end

  def create
    @dvd = Dvd.new(params[:dvd])

    if @dvd.save
      redirect_to @dvd, notice: 'Dvd was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @dvd.update_attributes(params[:dvd])
      redirect_to @dvd, notice: 'Dvd was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @dvd.destroy
    redirect_to dvds_url, notice: 'Dvd was successfully deleted.'
  end

  private

  def find_dvd
    @dvd = Dvd.find_by_id(params[:id])
    redirect_to dvds_url, :flash => {:error => 'Dvd not found.'} unless @dvd
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/dvds_helper.rb
module DvdsHelper

  def action_links(dvd)
    [link_to('Delete', dvd_path(dvd), :confirm => 'Are you sure?', :method => :delete), link_to_amazon(dvd)].compact.join(" | ")
  end

  def link_to_amazon(dvd, link_title='View on Amazon')
    dvd.asin.blank? ? nil : link_to(link_title, "http://www.amazon.com/dp/#{dvd.asin}")
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/actors/_form.html.haml
= form_for @actor do |f|
  - if @actor.errors.any?
    #error_explanation
      %h3= "#{pluralize(@actor.errors.count, "error")} prohibited this actor from being saved:"
      %ul
        - @actor.errors.full_messages.each do |msg|
          %li= msg

  %div
    = f.label :name, :class => "required"
    = f.text_field :name

  %div
    = f.label :gender, :class => "required"
    - Person::GENDERS.each do |gender|
      = label gender.to_sym, gender, :class => "radio inline"
      = f.radio_button :gender, gender
  %br

  %div
    = f.label :date_of_birth_at
    = f.date_select :date_of_birth_at, :start_year => 1900

  %div
    = f.label "Movies"
    = select_tag "actor[dvd_ids]", options_for_select(Dvd.all.map { |dvd| [dvd.name, dvd.id] }, @actor.dvds.map { |actor| actor.id}), {:multiple=>true, :size=>6}

  %br
    = f.submit :class => "btn btn-primary"

app/views/actors/edit.html.haml
%h1 Editing actor

= render 'form'

= link_to 'Show', @actor
\|
= link_to 'Back', actors_path

app/views/actors/index.html.haml
%h2 Actors
%br
= link_to 'Add a New Actor', new_actor_path

%table{:class => "table table-striped table-bordered"}
  %tr
    %th
      Name
    %th
      Born on
    %th
      Gender

    %th
      Dvd Count

    %th
      Actions

  - @actors.each do |actor|
    %tr
      %td
        =link_to(actor.name, actor_path(actor))
      %td
        =actor.date_of_birth_at.pretty_format
      %td
        =actor.gender
      %td
        =actor.dvds.length
      %td
        =link_to('Delete', actor_path(actor), :confirm => 'Are you sure?', :method => :delete)

app/views/actors/new.html.haml
%h1 New actor

= render 'form'

= link_to 'Back', actors_path

app/views/actors/show.html.haml
%h3= @actor.name
%br

%p
  %b Born on:
  = @actor.date_of_birth_at.pretty_format

%p
  %b Gender:
  = @actor.gender

%p
  %b Movies:
  %br
  =raw @actor.dvds.map(&:name).join("</br>")

= link_to 'Edit', edit_actor_path(@actor)
\|
= link_to 'Back', actors_path

app/views/directors/_form.html.haml
= form_for @director do |f|
  - if @director.errors.any?
    #error_explanation
      %h3= "#{pluralize(@director.errors.count, "error")} prohibited this director from being saved:"
      %ul
        - @director.errors.full_messages.each do |msg|
          %li= msg

  %div
    = f.label :name, :class => "required"
    = f.text_field :name

  %div
    = f.label :gender, :class => "required"
    - Person::GENDERS.each do |gender|
      = label gender.to_sym, gender, :class => "radio inline"
      = f.radio_button :gender, gender
  %br

  %div
    = f.label :date_of_birth_at
    = f.date_select :date_of_birth_at, :start_year => 1900

  %br
    = f.submit :class => "btn btn-primary"

app/views/directors/edit.html.haml
%h1 Editing director

= render 'form'

= link_to 'Show', @director
\|
= link_to 'Back', directors_path

app/views/directors/index.html.haml
%h2 Directors
%br
= link_to 'Add a New Director', new_director_path

%table{:class => "table table-striped table-bordered"}
  %tr
    %th
      Name
    %th
      Born on
    %th
      Gender
    %th
      Dvd count
    %th
      Actions

  - @directors.each do |director|
    %tr
      %td
        =link_to(director.name, director_path(director))
      %td
        =director.date_of_birth_at.pretty_format
      %td
        =director.gender
      %td
        =director.dvds.length
      %td
        =link_to('Delete', director_path(director), :confirm => 'Are you sure?', :method => :delete)

app/views/directors/new.html.haml
%h1 New director

= render 'form'

= link_to 'Back', directors_path

app/views/directors/show.html.haml
%h3= @director.name
%br

%p
  %b Born on:
  = @director.date_of_birth_at.pretty_format

%p
  %b Gender:
  = @director.gender

%p
  %b Movies:
  %br
  =raw @director.dvds.map(&:name).join("</br>")

= link_to 'Edit', edit_director_path(@director)
\|
= link_to 'Back', directors_path

app/views/dvds/_form.html.haml
= form_for(@dvd) do |f|
  - if @dvd.errors.any?
    %div{:id => "error_explanation"}
      %h3 #{ pluralize(@dvd.errors.count, "error") } prohibited this dvd from being saved:

      %ul
        - @dvd.errors.full_messages.each do |msg|
          %li= msg

  %div
    = f.label :name, :class => "required"
    = f.text_field :name

  %div
    = f.label :release_date_at
    = f.date_select :release_date_at, :start_year => 1900

  %div
    = f.label :summary, :class => "required"
    = f.text_area :summary

  %div
    = f.label :asin
    = f.text_field :asin

  %div
    = f.label "director"
    = f.collection_select(:director_id, Director.all, :id, :name, :include_blank => "Choose a director")

  %div
    = f.label "actors"
    = select_tag "dvd[actor_ids]", options_for_select(Actor.all.map { |actor| [actor.name, actor.id] }, @dvd.actors.map { |actor| actor.id}), {:multiple=>true, :size=>6}

  %br
    = f.submit :class => "btn btn-primary"

app/views/dvds/edit.html.haml
%h1 Editing dvd

= render 'form'

= link_to 'Show', @dvd
|
= link_to 'Back', dvds_path

app/views/dvds/index.html.haml
%h2 Dvds
%br
= link_to 'Add a New Dvd', new_dvd_path

%table{:class => "table table-striped table-bordered"}
  %tr
    %th
      Name
    %th
      Release Date
    %th
      Director
    %th
      Actor Count
    %th
      Summary
    %th
      Actions

  - @dvds.each do |dvd|
    %tr
      %td
        =link_to(dvd.name, dvd_path(dvd))
      %td
        =dvd.release_date_at.pretty_format
      %td
        =dvd.director.try(:name)
      %td
        =dvd.actors.length
      %td
        =truncate(dvd.summary, :length => 75)
      %td
        =raw action_links(dvd)

app/views/dvds/new.html.haml
%h1 New dvd

= render 'form'

= link_to 'Back', dvds_path

app/views/dvds/show.html.haml
%h3= @dvd.name
%br

%p
  %b Release date:
  = @dvd.release_date_at.pretty_format

%p
  %b Summary:
  = @dvd.summary

%p
  %b Asin:
  = link_to_amazon(@dvd, @dvd.asin)

%p
  %b Director:
  = @dvd.director.try(:name)

%p
  %b Actors:
  %br
  =raw @dvd.actors.map(&:name).join("</br>")

= link_to 'Edit', edit_dvd_path(@dvd)
|
= link_to 'Back', dvds_path

app/views/layouts/_header.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "DVD Manager"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
%a.btn.btn-navbar{"data-toggle"=>"collapse", "data-target"=>".nav-collapse"}
= link_to "DVD Manager", root_path, :class => 'brand'
%div.nav-collapse
  %ul.nav
    %li= link_to("Dvds", dvds_url)
    %li= link_to("Actors", actors_url)
    %li= link_to("Directors", directors_url)

app/views/layouts/application.html.haml
= render 'layouts/header'
%body
  %div.navbar.navbar-fixed-top
    %div.navbar-inner
      .container-fluid
        = render 'layouts/navigation'
  #main{:role => "main"}
    .container
      .content
        .row
          .span12
            = render 'layouts/messages'
            = yield
        %footer